### ISSUE TITLE
[BUG] некоректна печалба/загуба при продажба на акции чрез няколко сделки

### ISSUE THREAD

**Issue by micobg** [doino-gretchenliev/revolut-stocks#14]
При изчисляването на печалба/загуба от дадена сделка се взема като цена на придобиване [средната цена на акция](https://github.com/doino-gretchenliev/revolut-stocks/blob/391972c478253e91b7412c17fb85e1bb4c84f122/libs/calculators/utils.py#L9) на база записите в [`stock_queue`](https://github.com/doino-gretchenliev/revolut-stocks/blob/391972c478253e91b7412c17fb85e1bb4c84f122/libs/calculators/default.py#L56). Но това дава правилна цена само при първата продажба, когато все още в `stock_queue` са налични всички покупки на текущо притежаваните акции.
При продажба [`adjust_quantity`](https://github.com/doino-gretchenliev/revolut-stocks/blob/391972c478253e91b7412c17fb85e1bb4c84f122/libs/calculators/utils.py#L30) променя списъка, како премахва продадените акции по реда на закупуването им, вместо пропорционално от всички покупки, като по този начин изкривява средната цена на закупуване за следващите продажби.

**Един нагледен пример:**

> 1. BUY 100 x 1$ = -100$
> 2. BUY 60 x 1,2$ = -72$
> 3. SELL 80 x 1,5$ = +120$
> 4. SELL 80 x 2$ = +160$

Тук очевидно сме похарчили 172$ и сме спечелили 280$, което прави **108$ печалба**.

**В момента изчисленията стават по следния начин:**

:three: `SELL 80 x 1,5$ = +120$`:
В `stock_queue` имаме:
> 1. BUY 100 x 1$
> 2. BUY 60 x 1,2$

Това прави средна цена от _1,075$_ на акция. Следователно 86$ за 80 акции или печалба от 120 - 86 = **34$**
След това идва проблемният момент, в който тези 80 акции се вадят само от първата сделка.

:four: `SELL 80 x 2$ = +160$`:
В `stock_queue` вече имаме:
> 1. BUY 20 x 1$
> 2. BUY 60 x 1,2$

Това прави средна цена от _1,15$_ на акция. Следователно 92$ за 80 акции или печалба от 160 - 92 = **68$**

Така накрая се получава 34 + 68 = **102$ печалба** за деклариране.

Това е примерът в код за тестване:
```python
from datetime import datetime
from decimal import Decimal

from libs.calculators.default import calculate_win_loss

statements = [{
    'activity_type': 'BUY',
    'symbol': 'TEST',
    'price': Decimal(1.0),
    'exchange_rate': Decimal(1.6),
    'quantity': Decimal(100.0),
    'amount': Decimal(100.0),
    'trade_date': datetime.now(),
}, {
    'activity_type': 'BUY',
    'symbol': 'TEST',
    'price': Decimal(1.2),
    'exchange_rate': Decimal(1.6),
    'quantity': Decimal(60.0),
    'amount': Decimal(72.0),
    'trade_date': datetime.now(),
}, {
    'activity_type': 'SELL',
    'symbol': 'TEST',
    'price': Decimal(1.5),
    'exchange_rate': Decimal(1.6),
    'quantity': Decimal(80.0),
    'amount': Decimal(120.0),
    'trade_date': datetime.now(),
}, {
    'activity_type': 'SELL',
    'symbol': 'TEST',
    'price': Decimal(2.0),
    'exchange_rate': Decimal(1.6),
    'quantity': Decimal(80.0),
    'amount': Decimal(160.0),
    'trade_date': datetime.now(),
}]

sales, _ = calculate_win_loss(statements)

profit = sum(s['profit_in_currency'] for s in sales)

print(profit)
```

Едно възможно решение е вместо `stock_queue` да има само един запис, в който да са всички текущо притежавани акции, а цената да се осреднява само при добавяне на нови, а при изваждане да остава непроменена.

**Comment by mrmefbg** [comment]
В описанието в дадено, че работи като FIFO,  но правилното е средна цена при извлечение където не се опоменава от кой сет се продава.

**Comment by doino-gretchenliev** [comment]
Разбирам написаното от Вас, но в края на всяко извлечение от Revolut e посочен начина на осчетоводяване: 
![image](https://user-images.githubusercontent.com/7327247/107808501-5f72f200-6d72-11eb-8cb3-c546d346c333.png)
Поради тази причина калкулаторът работи коректно, използвайки FIFO.

**Comment by micobg** [comment]
Но това няма да е коректна справка за пред НАП, нали?

**Comment by doino-gretchenliev** [comment]
Напротив. Този текст указва начина за калкулиране на продадените дялове за данъчни цели.

**Comment by micobg** [comment]
Това е методът използван от Револют при генерирането на отчетите, но изискването според българския закон е да се използва средно претеглена цена.

> ЗАКОН ЗА ДАНЪЦИТЕ ВЪРХУ ДОХОДИТЕ НА ФИЗИЧЕСКИТЕ ЛИЦА
> Чл. 33. (4) Реализираната печалба/загуба по ал. 3 за всяка сделка се определя, като продажната цена се намалява с цената на придобиване на финансовия актив. Когато финансови активи от един вид, издадени от едно лице, са с различни цени на придобиване и впоследствие се продава част от тях и не може да бъде доказано коя част се продава, цената на придобиване на всеки един от тях е средно претеглената цена, определена въз основа на цената на придобиване на държаните към датата на продажбата финансови активи от същия вид и издател.

Някои брокери дават възможност за избор кой метода се използва, но в Револют не виждам такава опция. [Въпросът](https://community.revolut.com/t/revolut-trading-how-to-change-the-default-tax-lot-disposition-method/188615) вече е задаван в Revolut Community, но е без отговор.

**Comment by doino-gretchenliev** [comment]
Калкулаторът пресмята средната цена на придобиване според закона, който и Вие сте цитирали. Въпросът на това issue касаеше метода, по- който се продават дялове придобити на различни дати. Този механизъм се определя от брокерите. Затова калкулаторът следва оказания от Revolut метод.

**Comment by mrmefbg** [comment]
Интеграцията с T212 и други стейтмънти без конкретни лотове как може да стане.
