### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by skilldeliver** [doino-gretchenliev/revolut-stocks#15]
**Bug description**:
When I did an installation of the requirements I saw an error message in the logs:
`ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.`

I see that this is an issue for which it is made a PR: for https://github.com/doino-gretchenliev/revolut-stocks/pull/13

**To Reproduce**
Using Ubuntu 20.04 LTS with WSL and Python 3.8.5 I executed this command inside the root of the project: `python -m pip install -r requirements.txt`

**Expected behavior**
The expected behavior is not to show errors.

**Desktop**
Ubuntu 20.04 LTS with WSL

**Comment by doino-gretchenliev** [comment]
The PR was merged. [Here](https://github.com/doino-gretchenliev/revolut-stocks/pull/13#issuecomment-778642428) you can find more information.
