### ISSUE TITLE
[BUG] Multiple parsers don't generate statements.csv

### ISSUE THREAD

**Issue by mrmefbg** [doino-gretchenliev/revolut-stocks#16]
statements.csv is not generated in the output folder when selecting both revolut and T212. Individual parsers generate the file with no issues. I'm using the exe file, if the output folder is the same as exe there is no statement.csv in root folder, if I select a different sub-folder for results then the csv file is there.

**Comment by doino-gretchenliev** [comment]
Please, confirm you're using the [directory structure required](https://github.com/doino-gretchenliev/revolut-stocks#run-multiple-parsers). Keep in mind that with multiple parsers selected, `statements.csv` files for each parser are organized into sub-directories of the output directory.

Please, provide any errors that you're receiving and follow the BUG template.

**Comment by mrmefbg** [comment]
I found the statements.csv per parser in the sub-folders. Is it possible to combine them in root folder similar to xml and other csv output structures?

**Comment by doino-gretchenliev** [comment]
Thank you for following up on this issue.No. That behavior is intentional. I find it easier to have them separated in directories for each parser. In the future, there might be more files per parser, so I don't want to introduce a complex naming convention for each file type.
