### ISSUE TITLE
[FEATURE] Launch this project as an API

### ISSUE THREAD

**Issue by skilldeliver** [doino-gretchenliev/revolut-stocks#18]
Hello,  I would like to suggest building this project as an API. 
Maybe https://fastapi.tiangolo.com/ is a good choice if the project goes in this direction.

After that this API can have different clients consuming it - desktop gui, web app, etc...
Any thoughts, opinions, concerns?

Regards,
Vladi

**Comment by doino-gretchenliev** [comment]
Thank you for your suggestion. I don't see a reason for this project to be launched as API. I don't have the intention to develop a WEB UI, because of the legal complications. My idea is to keep the application simple as it could be in order to be able to support it properly.
