### ISSUE TITLE
[BUG] Calculator does not respect renamed (delisted) stocks

### ISSUE THREAD

**Issue by DimitarPetrov** [doino-gretchenliev/revolut-stocks#19]
**Describe the bug**
If you have bought a stock that is then delisted I have observed a kind of renaming record in the statements which the calculator does not take into account and then does not properly calculate the buy/sell position.

Example - OAS (Oasis Petroleum):
When bought there are the following records:
![image](https://user-images.githubusercontent.com/26522214/108603628-b3548b00-73b1-11eb-8d2d-821344fff6fd.png)

But after a few months, the stock was delisted from revolut, but you can still sell your position:
![image](https://user-images.githubusercontent.com/26522214/108603643-cebf9600-73b1-11eb-81db-84fe4017cdc9.png)

However, this sell is associated with a different ticker and there is some kind of renaming record in the statement.

**To Reproduce**
Just generate a report for statements containing such a stock.

**Expected behavior**
The sell and the buy to be correlated, currently, the following logs are observed:
```
[WARNING]: No purchase information found for: [OASPQ].
```
I would expect the rename to be taken into account and the sell to be correlated with its corresponding buy action.

**Desktop (please complete the following information):**
 - OS: MacOS in Docker
 - Version: `0.4.0`.

**Comment by doino-gretchenliev** [comment]
The issue should be fixed in version [0.5.0](https://github.com/doino-gretchenliev/revolut-stocks/releases/tag/0.5.0).
