### ISSUE TITLE
[BUG] Missing support for CANCEL activities + Changed Symbols in Revolut

### ISSUE THREAD

**Issue by ttsvv** [doino-gretchenliev/revolut-stocks#21]
Hello!
I have some SELL CANCEL activities in my Revolut statements, which cause script errors (It executes SELL activity, which is not supposed to do). Additionally one of my stocks has changed its symbol, which is not properly handled (The reported activity is "SC"). I'm attaching samples from my statements + scripts update that worked for me - you can use it if you like it!
I've hardcoded the symbol change for my declaration, the cancel activity is handled more properly.

Thanks for the good tool btw :-)

<img width="1162" alt="Screenshot 2021-03-21 at 3 29 33" src="https://user-images.githubusercontent.com/81057463/111891046-1446a180-89f8-11eb-9639-e606c43c0041.png">

<img width="1147" alt="Screenshot 2021-03-21 at 3 41 47" src="https://user-images.githubusercontent.com/81057463/111891025-cd58ac00-89f7-11eb-9429-3390142b01b9.png">

[modified_sources.zip](https://github.com/doino-gretchenliev/revolut-stocks/files/6176689/modified_sources.zip)

**Comment by doino-gretchenliev** [comment]
Both issues should be fixed in version [0.5.0](https://github.com/doino-gretchenliev/revolut-stocks/releases/tag/0.5.0).
