### ISSUE TITLE
[BUG] CSV Parser Requires Undocumented Column

### ISSUE THREAD

**Issue by l18m** [doino-gretchenliev/revolut-stocks#23]
**Describe the bug**
I am using the CSV parser to generate statements from my IB and E*TRADE accounts. I created manually a CSV file which I want to use as an input to the CSV parser. Upon executing the latter requires column `symbol_description` which is not mentioned in the README.md.

**To Reproduce**
1. Use the following csv:
```
trade_date,activity_type,company,symbol,quantity,price,amount
30.10.2020,BUY,Hecla Mining Inc.,HL,215,4.64,997.83
17.12.2020,SELL,Hecla Mining Inc.,HL,215,6.36,1344.8
```

2. Run `python3 stocks.py -i ~/Desktop/input-dir -o ~/Desktop/output-dir -p csv`

3. You will get:
```
Traceback (most recent call last):
  File "stocks.py", line 51, in <module>
    main()
  File "stocks.py", line 46, in main
    parsed_args.in_currency,
  File "/<some-path>/Projects/revolut-stocks/libs/process.py", line 62, in process
    statements[parser_name] = supported_parsers[parser_name](parser_input_dir).parse()
  File "/<some-path>/Projects/revolut-stocks/libs/parsers/csv.py", line 98, in parse
    activities = self.extract_activities(viewer)
  File "/<some-path>/Projects/revolut-stocks/libs/parsers/csv.py", line 73, in extract_activities
    "symbol_description": row[headers["symbol_description"]],
KeyError: 'symbol_description'
``` 
I don't see anything about `symbol_description` and it is not mandatory in `CSV_REQUIRED_COLUMNS`.

NOTE: I "**fixed**" it by deleting line `csv.py#73`.

**Expected behavior**
I expect the parser to work without specifying this column.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10bc324ed7a62d9e34ce88c801033af7e4d0f73b

**Comment by doino-gretchenliev** [comment]
The symbol description column became mandatory since the introduction of SC activities. I've documented the column and added it to CSV_REQUIRED_COLUMNS.
