### ISSUE TITLE
[BUG] Crashes when only SSP activity is in a Revolut report (TypeError: list indices must be integers or slices, not NoneType)

### ISSUE THREAD

**Issue by aqos156** [doino-gretchenliev/revolut-stocks#25]
**Describe the bug**
The parser crashes with `TypeError: list indices must be integers or slices, not NoneType` when (probably, I'm not python dev) only SSP activity is included in a Revolut statement.

Also this might be a reason for #22 and probably will happen if any of the `REVOLUT_OUT_OF_ORDER_ACTIVITY_TYPES` is only present in the report.

**To Reproduce**
Have an input pdf where the only activity is SSP. Or take a look at the attached pprint of `statements` before crash with redacted quantity (I assume it is not needed).

```
[[{'activity_type': 'SSP',
   'amount': Decimal('0.00'),
   'company': 'CALLON PETE CO DEL COM',
   'currency': 'USD',
   'price': Decimal('1.914794'),
   'quantity': Decimal('xxx'),
   'settle_date': datetime.datetime(2020, 6, 12, 0, 0),
   'symbol': 'CPE',
   'symbol_description': 'CPE - CALLON PETE CO DEL  COM - CA-Rev.SS:Surrender '
                         'old shs',
   'trade_date': datetime.datetime(2020, 6, 10, 0, 0)},
  {'activity_type': 'SSP',
   'amount': Decimal('0.00'),
   'company': 'CALLON PETE CO DEL COM',
   'currency': 'USD',
   'price': Decimal('19.14794'),
   'quantity': Decimal('xxx'),
   'settle_date': datetime.datetime(2020, 6, 12, 0, 0),
   'symbol': 'CPE',
   'symbol_description': 'CPE - CALLON PETE CO DEL  COM - CA-Rev.SS:Add new '
                         'shs.(CPE:10->1)',
   'trade_date': datetime.datetime(2020, 6, 10, 0, 0)}]]
```

**Expected behavior**
To work as expected

**Screenshots**
![Snímek obrazovky 2021-04-12 v 17 25 29](https://user-images.githubusercontent.com/11147374/114419855-1691bb00-9bb4-11eb-8015-5510b5f98125.png)

From what I see the for cycle inside `self.get_first_non_ssp_activity_index` returns None => therefor the NoneType error

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11cd317397f3a87dd76f2f76a9d538a3a0d5dc3a

**Comment by doino-gretchenliev** [comment]
The bug should be now fixed. Can you test with branch `only-ssp-bug-fix`?

**Comment by aqos156** [comment]
@doino-gretchenliev I now get the following error `[ERROR]: No previous purchase information found for out of order activities.`

**Comment by aqos156** [comment]
Just to clarify. I have a folder containing 10 pdf files, where one of them contains only the offending dataset.

**Comment by doino-gretchenliev** [comment]
Try renaming your statement files by their months. For example: January = 1.pdf, February = 2.pdf and etc. In case you have all SSP in a single file the sorting algorithm is I've used is a dummy one. A more sophisticated solution will require a lot more complex algorithm. Since that case is rare I'll include a note in the documentation that the user should sort their files.

**Comment by aqos156** [comment]
I can confirm that this sorting workaround together with the fix indeed solved the issue for me.

**Comment by doino-gretchenliev** [comment]
Thank you for your testing. The fix is now merged.
