### ISSUE TITLE
[QUESTION] Tax lot disposition and average price

### ISSUE THREAD

**Issue by vzlatev** [doino-gretchenliev/revolut-stocks#26]
First great tool - congrats for taking the time to develop it! 

Revolut statements show that tax should be calculated based on FIFO method but what I observe in get_avg_purchase_price() seems like average price for the stock. Let me give more practical example:

1) On "Date 1" we buy 0.4 shares from "Stock A".
Share price - $118.45
Trade price - $47.38

2) On "Date 2" we buy additional 1 share from "Stock A"
Share price - $246.22
Trade price - $246.22

2.1) In total we have now 1.4 shares from Stock A.

3) On "Date 3" we sell 1 share from "Stock A"
Share price - $273.18
Trade price - $273.18

If we follow FIFO rule we sell shares obtained on Date 1, calculate the profit and then sell from batch of shares obtained on Date 2 and calculate profit again. These are two separate SELL deals for the same stock. In this case I believe that on Form 5 in NRA tax form we should add them on two separate rows. 

With current logic what happens is that profit from both deals is added together and then divided by 2 which does not give the correct amount. 

Also another issue which I noticed is that Revolut seems to have some odd way to deduct SEC and TAF fees. They appear on the statement as SELL operation. In the export XML file these fees are calculated as a loss - I am not sure but fees may not be subject to deduction, this has to be verified with accountant. 

Please note that I'm not a professional accountant and above information is based purely on assumption.

**Comment by doino-gretchenliev** [comment]
The FIFO rule is applied to the way the assets are disposed and it's stated by Revolut. According to Bulgarian law, the purchase price should be the average purchase price of each asset. The sell operation is always reported as is, you can't divide it into multiple sell operations.

The tax and fees are calculated according to the official response from NAP to my request for clarification of the law.

**Comment by vzlatev** [comment]
@doino-gretchenliev Thanks for the reply. If you have official response this ends the discussion even though if I worked in NRA I would argue based on the following:

1. After brief research I can see that law says "If you **can't prove** which asset is sold then you use weighted average price..." 
2. If we know the asset acquisition date and you know that FIFO rule is applied then logically we can easily calculate prices for each sale deal and how many assets we have to write off from our portfolio. After all they are in chronological order - the first bought are the first sold. 

Revolut reports show sell operation on single row but this does not mean that you can't calculate from which batch does the asset come from if you use excel or pen and sheet of paper - thats all. 

I won't dwell further into this, I just wanted to check what is your interpretation of this problem.
