### ISSUE TITLE
[Question] What does the `-c` argument actually do and possible enhancements.

### ISSUE THREAD

**Issue by aqos156** [doino-gretchenliev/revolut-stocks#27]
# Question
The title speaks for itself, the description of `-c` argument seems quite vague to me. Does it do any conversion? Is there a tax applied on it? Is it just the pure result of FIFO working with the currency in parsed reports? That means that if all of my Revolut reports have the USD currency in it, the -c just displays it? Shouldn't it be the default behavior?

```
-c                    Show profit/loss in currency.
```

I know it is developed according to Bulgarian laws, but maybe make this calculator by default display the result in the currency of the report, mark it clearly for example as:

```
Result of FIFO calculations: xxx USD/GBP/CZK/LEV
```

this would be useful to many people and add a flag that turns on the country specific (Bulgarian) output.

And last enhancement I can think of is maybe display some statistics (if possible) just to confirm whether everything works ok.

```
You have 4 open positions in: AMZN, CPE, GME, AMC

Statistics for year 2020 - Year ended
------------------------
Closed trades: xxx
Open positions left: xxx
Profit: -xxx

Statistics for year 2021 - Year in progress
-----–--––-------------
Closed trades: xxx
Open positions left: xxx
Profit: -xxx
```

**Comment by doino-gretchenliev** [comment]
The `-c` option displays the total profit or the loss in USD. It follows the FIFO rule, but the way it's calculated is based on Bulgarian law. The purpose of the calculation is to provide tax calculations, so no other statistics will be included. More currencies won't be included, because calculation accuracy can't be guaranteed.
