### ISSUE TITLE
[BUG] Revolut parser not working anymore

### ISSUE THREAD

**Issue by ognyanstoimenov** [doino-gretchenliev/revolut-stocks#30]
**Describe the bug**
Looks like Revolut changed their statement format and the script always outputs "[ERROR]: Not activities found with parser[revolut]. Please, check the statement files."

**Comment by gkodinov** [comment]
yes, I get this when I try parsing my statement:

`python3 stocks.py -i revolut -o revolut-out
[INFO]: Parsing statement files with parsers: ['revolut'].
[INFO]: Collected statement files for processing: ['revolut/0855B379-3631-40B2-B243-D4F22B4A16E5.pdf', 'revolut/0DFA5F35-54DB-4C31-B147-426CEAAE48D9.pdf', 'revolut/16EDD70B-ACAF-43E8-A363-7AC3250FEDD8.pdf', 'revolut/295CA8F3-651B-4433-A88F-5B6ABCF13197.pdf', 'revolut/3827CCA3-BA05-4F8A-BA50-E03F105C0F32.pdf', 'revolut/4E519A45-2E27-4996-B2A1-DEE4C74B1E8D.pdf', 'revolut/5FDB1B94-B252-40CE-AD25-C80BC64F6805.pdf', 'revolut/84BA6D4E-F8B7-444C-9204-4F8440888CFF.pdf', 'revolut/DF315C1F-9504-4EC4-8707-F55BD2B415C3.pdf'].
[ERROR]: Not activities found with parser[revolut]. Please, check the statement files.`

**Comment by gkodinov** [comment]
from the looks of it the structure of the reports generated by revolut is completely different.

**Comment by gkodinov** [comment]
can anybody provide a sample of the old report format? I'd like to give it a short to fixing the parser

**Comment by gkodinov** [comment]
this code is beyond salvation. it's better to just do it afresh

**Comment by doino-gretchenliev** [comment]
The app will support the new support Revolut Excel format in the near future.

**Comment by doino-gretchenliev** [comment]
CSV support is being developed on [this branch](https://github.com/doino-gretchenliev/revolut-stocks/tree/support-revolut-csv-format). The initial commit is successfully parsing and calculating all of the tax documents. The code still needs verification(Revolut is not providing some of the previously available information) and tests need fixing.

**Comment by doino-gretchenliev** [comment]
CSV support is now released: https://github.com/doino-gretchenliev/revolut-stocks/releases/tag/0.6.0.
