### ISSUE TITLE
Code does not work as intended

### ISSUE THREAD

**Issue by seralouk** [doino-gretchenliev/revolut-stocks#34]
Hi. I have downloaded the test csv file from here: https://github.com/doino-gretchenliev/revolut-stocks/blob/main/tests/functional/resources/input/test.csv

I then run: `python3 stocks.py -i /Users/sera/Desktop/test -o /Users/sera/Desktop/test` and I get as output:
```
(base) seralouk:revolut-stocks-main loukas$ python3 stocks.py -i /Users/loukas/Desktop/test -o /Users/loukas/Desktop/test
[INFO]: Parsing statement files with parsers: ['revolut'].
[INFO]: Collected statement files for processing: ['/Users/loukas/Desktop/test/test.csv'].
[]
None
[ERROR]: Not activities found with parser[revolut]. Please, check the statement files.
```

To overcome this, I tried `python3 stocks.py -i /Users/loukas/Desktop/test -o /Users/loukas/Desktop/test -p csv` and now i get:
```
[INFO]: Parsing statement files with parsers: ['csv'].
[INFO]: Collected statement files for processing: ['/Users/loukas/Desktop/test/test.csv'].
[ERROR]: Unable to parse date: [30.03.20].
```
a new error for the date

**Comment by doino-gretchenliev** [comment]
The test data is intended to be used by the automated test, so it's expected to be executed with specific options. Errors are also expected as they should be tested as well.

**Comment by seralouk** [comment]
> The test data is intended to be used by the automated test, so it's expected to be executed with specific options. Errors are also expected as they should be tested as well.

I see. Thank you!
