### ISSUE TITLE
bnb.bg не връща csv

### ISSUE THREAD

**Issue by bobcho** [doino-gretchenliev/revolut-stocks#4]
Това дали трябва да върне csv?

https://www.bnb.bg/Statistics/StExternalSector/StExchangeRates/StERForeignCurrencies/index.htm?downloadOper=true&group1=second&valutes=USD&search=true&showChart=false&showChartButton=false&type=CSV&periodStartDays=02&periodStartMonths=12&periodStartYear=2019&periodEndDays=02&periodEndMonths=03&periodEndYear=2020

Гледам, че дава html и след това гърми като го парсва:

revolut-stocks-calc_1  | [INFO]: Populating exchange rates.
revolut-stocks-calc_1  | Traceback (most recent call last):
revolut-stocks-calc_1  |   File "stocks.py", line 74, in <module>
revolut-stocks-calc_1  |     main()
revolut-stocks-calc_1  |   File "stocks.py", line 49, in main
revolut-stocks-calc_1  |     populate_exchange_rates(statements)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/exchange_rates.py", line 76, in populate_exchange_rates
revolut-stocks-calc_1  |     exchange_rates = get_exchange_rates(first_date, last_date)
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/exchange_rates.py", line 60, in get_exchange_rates
revolut-stocks-calc_1  |     exchange_rates.update(query_exchange_rates(curr_fs_date, curr_ls_date))
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/exchange_rates.py", line 48, in query_exchange_rates
revolut-stocks-calc_1  |     date = datetime.strptime(row[0], BNB_DATE_FORMAT)
revolut-stocks-calc_1  |   File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
revolut-stocks-calc_1  |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
revolut-stocks-calc_1  |   File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
revolut-stocks-calc_1  |     raise ValueError("time data %r does not match format %r" %
revolut-stocks-calc_1  | ValueError: time data ' ' does not match format '%d.%m.%Y'
revolut-stocks_revolut-stocks-calc_1 exited with code 1

Май не им работи тази функция в сайта в момента..

**Comment by doino-gretchenliev** [comment]
С [тази промяна](https://github.com/doino-gretchenliev/revolut-stocks/commit/dd421eaa4fbd3d07418851744a8b8700a05c20c6) се върща информация за грешката. В момента, сайтът БНБ блокира и не връща резултати. Ако това продължи да се случва и следващите дни има други services, които предлагат фиксинга на БНБ.

**Comment by doino-gretchenliev** [comment]
Fix with local cached exchange rates. https://github.com/doino-gretchenliev/revolut-stocks/commit/fd34b4e7be0dfed67bdd6f6cb7ac0072f35a4d5e
