### ISSUE TITLE
Parse pdf problem

### ISSUE THREAD

**Issue by nayots** [doino-gretchenliev/revolut-stocks#5]
### Steps to reproduce:

in root of cloned repo run
```
python stocks.py -i <path_to_input_dir> -o <path_to_output_dir>
```
with the replaced paths for your system

like
```
python stocks.py -i C:\Users\grigo\OneDrive\Documents\revolut\statements -o C:\Users\grigo\OneDrive\Documents\revolut\output
```

### Expected behavior:
The script generates the  expected output.

### Actual behavior:
Application crashes with:
![image](https://user-images.githubusercontent.com/10439945/106394023-fb137280-6402-11eb-9a3e-b26596ab5836.png)
![image](https://user-images.githubusercontent.com/10439945/106394030-06ff3480-6403-11eb-827b-88a9f921a8b0.png)
![image](https://user-images.githubusercontent.com/10439945/106394050-2ac27a80-6403-11eb-9607-ea4ae3e5800a.png)

**Comment by bobcho** [comment]
pr #2 оправя това

**Comment by maddrum** [comment]
Have the same issue, closed my task.

**Comment by doino-gretchenliev** [comment]
Thanks to @nayots , I was able to reproduce the issue. I'll post an update soon. PR2 is not a solution.

**Comment by bobcho** [comment]
I guess it depends on the statement file content - it works fine here. Or do you mean it is not the proper solution? Either way, looking forward for the fix, thanks!

**Comment by doino-gretchenliev** [comment]
The PR2 would fix the error, but not all activities would be parsed and so result in wrong calculations. The parsed activities could be checked by reviewing the statement.csv file, which is located in the output directory.

**Comment by doino-gretchenliev** [comment]
Parsing issues are resolved. SSP and MAS activities are supported now.
https://github.com/doino-gretchenliev/revolut-stocks/commit/e0bff741581581a85b0fe67dcc74ba40c6f39490
