### ISSUE TITLE
Unsupported activity types

### ISSUE THREAD

**Issue by astoimenov** [doino-gretchenliev/revolut-stocks#9]
I get an error: `[ERROR]: Statements contain unsupported activity types: ['SSP']. Please, check documentation.`

As I see it the SSP type is the stock split.

**Comment by doino-gretchenliev** [comment]
Yes, SSPs are the stock split events. Support for those activities is in development.

**Comment by alexanderpivanov** [comment]
Same here.

**Comment by doino-gretchenliev** [comment]
SSP and MAS activities are now supported.
https://github.com/doino-gretchenliev/revolut-stocks/commit/e0bff741581581a85b0fe67dcc74ba40c6f39490
